# Generated by Django 6.0.5 on 2026-05-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('SHIPPED', 'تم الشحن'), ('DELIVERED', 'تم التوصيل')], default='PENDING', max_length=20, verbose_name='حالة الشحنة')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('delivery_driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم مندوب التوصيل')),
                ('delivery_driver_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='هاتف المندوب')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم مركبة التوصيل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='العميل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='المنتج')),
            ],
        ),
    ]
